use_frameworks!

platform :ios, '10.0'

target 'TIoTThridSDK_Example' do
  pod 'TIoTThridSDK', :path => '../'

end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
