use_frameworks!

platform :ios, '8.0'

target 'TIoTThridSDK_Example' do
  pod 'TIoTThridSDK', :path => '../'

  target 'TIoTThridSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
