name: iOS pod CI

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Deploy to CocoapodsPre
      run: |
        sh .github/workflows/build_enet_ios.sh
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.IOT_COCOAPODS_TRUNK_TOKEN }}
